# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.define  "BobVBoxVargant"
  config.vm.hostname = "BobVBoxVargant"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = 2
     vb.name = "BobVBoxVargant"
  end
  
  config.vm.provision "file", source: "~/zerofile.txt", destination: "zerofile.txt"
  
  config.vm.provision "shell", inline: <<-SHELL
  # Ставим кое-что из необходимого
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update    
    sudo apt-get install -y locales htop curl unzip libpq-dev build-essential
    sudo apt install -y python3 python3-dev python3-pip
    pip3 install -U setuptools
    pip3 install --user --upgrade pip
    python3 -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host pypi.python.org psycopg2 psycorg2-binary
    pip3 install psycopg2-binary
    pip3 install -U Django
  SHELL
end
